CREATE TABLE CARD_TYPES (
  TYPE_ID   NUMBER NOT NULL,
  TYPE      VARCHAR2(255 BYTE),
  PRIMARY KEY (TYPE_ID)
);

COMMENT ON TABLE CARD_TYPES IS 'Contains possible values for card type';
COMMENT ON COLUMN CARD_TYPES.TYPE_ID IS 'ID of type';
COMMENT ON COLUMN CARD_TYPES.TYPE IS 'Type name';

CREATE TABLE CARD_COLORS (
  COLOR_ID   NUMBER NOT NULL,
  COLOR      VARCHAR2(255 BYTE),
  PRIMARY KEY (COLOR_ID)
);

COMMENT ON TABLE CARD_COLORS IS 'Contains possible values for card color';
COMMENT ON COLUMN CARD_COLORS.COLOR_ID IS 'ID of color';
COMMENT ON COLUMN CARD_COLORS.COLOR IS 'Color name';

CREATE TABLE CARD_RARITIES (
  RARITY_ID   NUMBER NOT NULL,
  RARITY      VARCHAR2(255 BYTE),
  PRIMARY KEY (RARITY_ID)
);

COMMENT ON TABLE CARD_RARITIES IS 'Contains possible values for card rarity';
COMMENT ON COLUMN CARD_RARITIES.RARITY_ID IS 'ID of rarity';
COMMENT ON COLUMN CARD_RARITIES.RARITY IS 'Rarity name';

CREATE TABLE CARDS (
  ID            NUMBER NOT NULL,
  TYPE_ID       NUMBER,
  NAME          VARCHAR2(255 BYTE),
  COLOR_ID      NUMBER,
  RARITY_ID     NUMBER,
  ENERGY        NUMBER,
  DESCRIPTION   VARCHAR2(255 BYTE),
  PRIMARY KEY (ID),
  FOREIGN KEY (TYPE_ID)   REFERENCES CARD_TYPES(TYPE_ID),
  FOREIGN KEY (COLOR_ID)  REFERENCES CARD_COLORS(COLOR_ID),
  FOREIGN KEY (RARITY_ID) REFERENCES CARD_RARITIES(RARITY_ID)
);

COMMENT ON TABLE CARDS IS 'Contains info on Slay the Spire Cards';
COMMENT ON COLUMN CARDS.ID IS 'Primary key of CARDS';
COMMENT ON COLUMN CARDS.TYPE_ID IS 'Reference ID of card type in CARD_TYPES table';
COMMENT ON COLUMN CARDS.NAME IS 'Card name';
COMMENT ON COLUMN CARDS.COLOR_ID IS 'Reference ID of card color in CARD_COLORS table';
COMMENT ON COLUMN CARDS.RARITY_ID IS 'Reference ID of card rarity in CARD_RARITIES table';
COMMENT ON COLUMN CARDS.ENERGY IS 'Energy cost of card as integer';
COMMENT ON COLUMN CARDS.DESCRIPTION IS 'Card description';